-- EcoLingo: esquema compatible, trazabilidad y Realtime para puntos limpios.
-- Puede ejecutarse sobre una instalación nueva o sobre la tabla original del proyecto.

create table if not exists public.recycling_points (
  id bigint generated by default as identity primary key,
  source text default 'mma',
  source_id text,
  name text not null,
  address text not null,
  commune text,
  region text,
  latitude double precision not null,
  longitude double precision not null,
  accepted_materials text[] not null default '{}',
  hours text,
  status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz default now(),
  last_verified_at timestamptz default now()
);

alter table public.recycling_points
  add column if not exists source text default 'mma',
  add column if not exists source_id text,
  add column if not exists updated_at timestamptz default now(),
  add column if not exists last_verified_at timestamptz default now(),
  add column if not exists status text;

-- La identidad real es fuente + id de la fuente. La restricción original por
-- coordenadas impediría conservar trazabilidad si dos fuentes comparten ubicación.
alter table public.recycling_points
  drop constraint if exists recycling_points_latitude_longitude_key;

drop index if exists public.recycling_points_coordinates_unique;
create unique index if not exists recycling_points_source_id_unique
  on public.recycling_points (source, source_id);

create index if not exists recycling_points_coordinates_idx
  on public.recycling_points (latitude, longitude);
create index if not exists recycling_points_last_verified_idx
  on public.recycling_points (last_verified_at desc);

alter table public.recycling_points enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'recycling_points'
      and policyname = 'Anyone can read official recycling points'
  ) then
    create policy "Anyone can read official recycling points"
      on public.recycling_points for select
      using (true);
  end if;
end $$;

grant usage on schema public to anon, authenticated, service_role;
grant select on public.recycling_points to anon, authenticated;
grant select, insert, update, delete on public.recycling_points to service_role;
grant usage, select on all sequences in schema public to service_role;

-- UPDATE/DELETE completos permiten al cliente reconciliar correctamente el mapa.
alter table public.recycling_points replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public'
         and tablename = 'recycling_points'
     ) then
    alter publication supabase_realtime add table public.recycling_points;
  end if;
end $$;
