-- Sugerencias de puntos limpios enviadas por la comunidad.
--
-- Sin esta tabla, el formulario "Sugerir Punto Limpio" falla siempre con
-- PGRST205 ("Could not find the table 'public.community_suggestions'").
--
-- La migración es idempotente: se puede ejecutar sobre una instalación nueva o
-- sobre uno de los proyectos donde la tabla ya se creó a mano desde el README.

create table if not exists public.community_suggestions (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  latitude double precision,
  longitude double precision,
  materials text[] not null default '{}',
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- Columnas que pueden faltar si la tabla venía de la versión del README.
alter table public.community_suggestions add column if not exists latitude double precision;
alter table public.community_suggestions add column if not exists longitude double precision;
alter table public.community_suggestions add column if not exists materials text[] not null default '{}';
alter table public.community_suggestions add column if not exists status text not null default 'pending';
alter table public.community_suggestions add column if not exists created_at timestamptz not null default now();

-- Coordenadas dentro de rango cuando se informan. El formulario ya lo valida,
-- pero la base de datos no debe depender de que el cliente se porte bien.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.community_suggestions'::regclass
      and conname = 'community_suggestions_coords_range'
  ) then
    alter table public.community_suggestions
      add constraint community_suggestions_coords_range check (
        (latitude is null or (latitude >= -90 and latitude <= 90))
        and (longitude is null or (longitude >= -180 and longitude <= 180))
      );
  end if;
end $$;

create index if not exists community_suggestions_status_idx
  on public.community_suggestions (status, created_at desc);

alter table public.community_suggestions enable row level security;

-- Cualquiera puede proponer un punto, siempre en estado 'pending'.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'community_suggestions'
      and policyname = 'Anyone can submit suggestions'
  ) then
    create policy "Anyone can submit suggestions"
      on public.community_suggestions for insert
      with check (status = 'pending');
  end if;
end $$;

-- Las policies de RLS no bastan: sin estos GRANT, PostgREST responde
-- 42501 "permission denied for table community_suggestions".
grant usage on schema public to anon, authenticated;
grant insert on public.community_suggestions to anon, authenticated;
grant usage, select on sequence public.community_suggestions_id_seq to anon, authenticated;

-- La moderación se hace con la clave de servicio, nunca desde el navegador.
grant select, insert, update, delete on public.community_suggestions to service_role;

-- Nadie anónimo debe poder leer las sugerencias de los demás: no se crea
-- ninguna policy de SELECT para anon a propósito.
